---
- name: "configure rsyslog - logentries"
  template:
    src: "logentries.conf.j2"
    dest: "/etc/rsyslog.d/{{ logentries_conf_name }}"
    owner: root
    group: root
    mode: 0644
  when: logentries_token | length > 0
  notify: "restart rsyslog"
  tags:
    - log-management

- name: "configure rsyslog - logz.io"
  template:
    src: "logzio.conf.j2"
    dest: "/etc/rsyslog.d/{{ logzio_conf_name }}"
    owner: root
    group: root
    mode: 0644
  when: logzio_token | length > 0
  notify: "restart rsyslog"
  tags:
    - log-management

- name: "configure rsyslog - papertrail"
  template:
    src: "papertrail.conf.j2"
    dest: "/etc/rsyslog.d/{{ papertrail_conf_name }}"
    owner: root
    group: root
    mode: 0644
  when: papertrail_host | length > 0
  notify: "restart rsyslog"
  tags:
    - log-management

- name: "configure rsyslog - simple tcp"
  template:
    src: "rsyslog_tcp.conf.j2"
    dest: "/etc/rsyslog.d/{{ rsyslog_conf_name }}"
    owner: root
    group: root
    mode: 0644
  when: rsyslog_tcp_host | length > 0
  notify: "restart rsyslog"
  tags:
    - log-management

- name: "configure rsyslog - nginx"
  template:
    src: "nginx.conf.j2"
    dest: "/etc/rsyslog.d/{{ rsyslog_nginx_conf_name }}"
    owner: root
    group: root
    mode: 0644
  when: rsyslog_nginx_tcp_host | length > 0
  notify: "restart rsyslog"
  tags:
    - log-management
